package com.example.XyhubCommon.enumType;

import java.util.Arrays;
import java.util.Optional;

public enum NotificationType {

	PROJECT_ASSIGN_ACCCES("PROJECTASSIGNACCCES"), PROJECT_ACCESS_REMOVE("PROJECTACCESSREMOVED"),
	TICKET_CREATED("TICKETCREATED"), TICKET_ASSIGNED("TICKETASSIGNED"), TICKET_INREVIEW("TICKETINREVIEW"),
	TICKET_RESOLVED("TICKETRESOLVED"), TICKET_CANCELLED_BY_ADMIN("TICKETCANCELLEDBYADMIN"),
	TICKET_CANCELLED_BY_USER("TICKETCANCELLEDBYUSER"), TICKET_REOPENED_BY_ADMIN("TICKETREOPENEDBYADMIN"),
	TICKET_REOPENED_BY_USER("TICKETREOPENEDBYUSER"), TICKET_EDITED_BY_USER("TICKETEDITEDBYUSER"),
	ATTACHMENT_ADDED_BY_ADMIN("ATTACHMENTADDEDBYADMIN"), ATTACHMENT_ADDED_BY_USER("ATTACHMENTADDEDBYUSER"),
	ATTACHMENT_ADDED_BY_ASSIGNEE("ATTACHMENTADDEDBYASSIGNEE"), COMMENTS_ADDED_BY_ADMIN("COMMENTSADDEDBYADMIN"),
	COMMENTS_ADDED_BY_USER("COMMENTSADDEDBYUSER"), COMMENTS_ADDED_BY_ASSIGNEE("COMMENTSADDEDBYASSIGNEE"),
	EMPLOYEE_CREATED("EMPLOYEECREATED"), JOB_CREATED("JOB CREATED SUCCESSFULL"),
	JOB_APPLOCATION_CREATED("job application is created"), SHEDULE_INTERVIEW_STATUS("changes interview status"),
	JOB_VENDOR_CREATED("JOBVENDORCREATED "),
	JOB_VENDOR_EDITED("JOBVENDOREDITED "),
	REMINDER_SENT("REMINDERSENT");
	private String value;

	NotificationType(String value) {
		this.value = value;
	}

	public String value() {
		return this.value;
	}

	public static NotificationType toEnum(String value) {
		Optional<NotificationType> optional = Arrays.stream(values()).filter(e -> e.value.equalsIgnoreCase(value))
				.findFirst();
		if (optional.isPresent())
			return optional.get();
		else
			throw new IllegalArgumentException(value + " is not a valid status");
	}
}